### ISSUE TITLE
Repack Tool and Package extractor

### ISSUE THREAD

**Issue by ghost** [thethiny/MK11-PackageExtractor#2]
Was able to compile and build everything, unfortunately the MK11PackageExtractor keeps giving an std::bad_alloc error and creates an empty output folder when trying to use it on a .xxx file. I've tried adding the dll_folder argument to point to the folder containing oo2core_5_win64.dll to no avail, the program gives me the same error. I'm quite new to c++ and I've tried looking through the code but I couldn't figure out the issue.

**Although**, I'm able to extract any .xxx and .psf file using [Id-Daemon's tool](https://forum.xentax.com/viewtopic.php?f=16&t=20126), which extracts everything including models along with morphs as well as textures, so in my opinion I think the best choice for an extractor would be to just use this tool. (Maybe focus on the repacker if you ever get the time to?)

As for the texture repacker, how exactly does this tool function? If there is a manual way to do this without using the repacker, are you able to document it since I don't quite understand the readme well. Do you need to manually modify the file with a hex editor and insert the new texture and if so, how exactly? Sorry for the long read, I'm quite new to c++ and this kind of stuff.

**Comment by thethiny** [comment]
You shouldn't point to folder, you should point to the dll directly.

**Comment by ghost** [comment]
Same error, is it working on ur end?

**Comment by thethiny** [comment]
Yes it works perfectly. Show me the command you're using.

**Comment by ghost** [comment]
I copied all the files including the .dll in one folder, so it would look smt like 

`MK11PackageExtractor -f GEARASSETS_SKA_ScriptAssets.xxx -d oo2core_5_win64.dll`

**Comment by thethiny** [comment]
Let me know if this one works
https://we.tl/t-S2WLK4P8B5

**Comment by ghost** [comment]
Works perfectly, I can extract everything without any errors now, awesome.

As for the repacker tool, are you able to detail how you can reimport a file into the .xxx archive? If you could that would be great, I didn't quite get how it works.

**Comment by thethiny** [comment]
You probably compiled it incorrectly. You need to compile it using the instructions I provided.
As for the repacker tool, Basically it just coverts files and then you manually insert them into the XXX. Follow the tutorial (or the Table) in the Readme.md file to be able to see where to put them back. Then run the tool. The tool needs to be recompiled everytime because it is specific for every file. I haven't updated it in a long while because I didn't figure out how to get the GUIDs for the files in the Bulk Data table.
